INHERIT: ../base.yml
site_name: Dise√±o de Interfaces Web - Apuntes y referencias
site_dir: ../../docs/referencias

plugins:
  - search:
      lang: es

# Page tree
nav:
  - Inicio: index.md
  - UD1: ud1.md
  # - UD2: ud2.md
  # - UD3: ud3.md
  # - UD4: ud4.md
  # - UD5:
  #     - ud5.md
  #     - ud5.1-Empezando-con-React.md
  #     - ud5.2-Paso-a-paso.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IESAlbertiCadiz
      name: IES Alberti en Twitter
